name: Notify weekly on Tuesday

on:
  push:

jobs:
  thu_weekly_on_notify:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      with:
        persist-credentials: ${{ secrets.SUSHI_GITHUB_TOKEN }}
    - name: Create local changes
      run: |
        touch test.txt
    - name: Commit & Push changes
      uses: actions-js/push@master
      with:
        github_token: ${{ secrets.SUSHI_GITHUB_TOKEN }}
