name: Notify weekly on Tuesday

on:
  push:

env:
  WP_GROUP_ID: 1245816086300488
  WP_TOKEN: ${{ secrets.WP_TOKEN }}

jobs:
  thu_weekly_on_notify:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      with:
        persist-credentials: ${{ secrets.SUSHI_GITHUB_TOKEN }}
    - name: Notify
      run: |
        date -d tomorrow '+%Y-%m/%d'
        env
    - name: Commit & Push changes
      uses: actions-js/push@master
      with:
        github_token: ${{ secrets.SUSHI_GITHUB_TOKEN }}
